#!/bin/bash

# Entrypoint script for CDK deployment with encrypted credentials

# Function to show usage
show_usage() {
    echo "🚀 CDK Deployment Container"
    echo ""
    echo "Usage:"
    echo "  docker run --rm app hash <access_key> <secret_key> <region>"
    echo "  docker run --rm app deploy <encrypted_credentials>"
    echo "  docker run --rm -it app shell <encrypted_credentials>"
    echo ""
    echo "Examples:"
    echo "  # Hash credentials (first time setup)"
    echo "  docker run --rm app hash AKIATYDCXTUVLGSA6HMK OinVuEzoBzSxQzDrn9KvYytRpoLjzgObYPaA2KnC us-east-1"
    echo ""
    echo "  # Deploy with encrypted credentials"
    echo "  docker run --rm app deploy QUtJQVRZRENYVFVWTEZTQTZITUs6T2luVnVFem9CelpTeFF6RHJuOUt2WXl0UnBvTGp6Z09iWVBhQTJLbkM6dXMtZWFzdC0x"
    echo ""
    echo "  # Interactive shell with AWS credentials"
    echo "  docker run --rm -it app shell QUtJQVRZRENYVFVWTEZTQTZITUs6T2luVnVFem9CelN4UXpEcm45S3ZZeXRScG9ManpnT2JZUGFBMktuQzp1cy1lYXN0LTE="
    echo ""
    echo "🔐 Security: Credentials are encrypted using base64 encoding for sharing"
}

# Main script logic
case "$1" in
    "hash")
        if [ $# -ne 4 ]; then
            echo "❌ Error: hash command requires 3 arguments (access_key, secret_key, region)"
            show_usage
            exit 1
        fi
        
        ACCESS_KEY="$2"
        SECRET_KEY="$3"
        REGION="$4"
        
        echo "🔐 Creating encrypted credentials hash..."
        ENCRYPTED=$(python3 encrypt_utils.py hash "$ACCESS_KEY" "$SECRET_KEY" "$REGION" | grep "Hash:" | cut -d' ' -f2)
        echo "✅ Encrypted credentials hash:"
        echo "$ENCRYPTED"
        echo ""
        echo "📋 Use this hash for deployment:"
        echo "docker run --rm app deploy $ENCRYPTED"
        ;;
        
    "deploy")
        if [ $# -ne 2 ]; then
            echo "❌ Error: deploy command requires 1 argument (encrypted_credentials)"
            show_usage
            exit 1
        fi
        
        ENCRYPTED_CREDS="$2"
        
        echo "🔓 Decrypting credentials..."
        DECRYPTED_OUTPUT=$(python3 encrypt_utils.py decrypt "$ENCRYPTED_CREDS" 2>&1)
        
        if echo "$DECRYPTED_OUTPUT" | grep -q "Error:"; then
            echo "❌ $DECRYPTED_OUTPUT"
            echo ""
            echo "💡 Troubleshooting:"
            echo "1. Make sure you're using the exact hash generated by the 'hash' command"
            echo "2. Check that the hash hasn't been modified or truncated"
            echo "3. Try generating a new hash with: docker run --rm app hash <access_key> <secret_key> <region>"
            exit 1
        fi
        
        # Extract credentials from Python output
        ACCESS_KEY=$(echo "$DECRYPTED_OUTPUT" | grep "Access Key:" | cut -d' ' -f3)
        SECRET_KEY=$(echo "$DECRYPTED_OUTPUT" | grep "Secret Key:" | cut -d' ' -f3)
        REGION=$(echo "$DECRYPTED_OUTPUT" | grep "Region:" | cut -d' ' -f2)
        
        if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ] || [ -z "$REGION" ]; then
            echo "❌ Error: Failed to extract credentials from decryption output"
            echo "Debug output: $DECRYPTED_OUTPUT"
            exit 1
        fi
        
        echo "✅ Credentials decrypted successfully"
        echo "🌍 Region: $REGION"
        
        # Configure AWS CLI
        echo "⚙️  Configuring AWS CLI..."
        aws configure set aws_access_key_id "$ACCESS_KEY"
        aws configure set aws_secret_access_key "$SECRET_KEY"
        aws configure set region "$REGION"
        aws configure set output json
        
        # Test AWS connection
        echo "🔍 Testing AWS connection..."
        if aws sts get-caller-identity > /dev/null 2>&1; then
            echo "✅ AWS connection successful"
            IDENTITY=$(aws sts get-caller-identity --query 'Arn' --output text)
            echo "👤 Identity: $IDENTITY"
        else
            echo "❌ AWS connection failed. Please check your credentials."
            exit 1
        fi
        
        # List Lambda functions to verify permissions
        echo "📋 Checking existing Lambda functions..."
        aws lambda list-functions --query 'Functions[?contains(FunctionName, `tracer`)].FunctionName' --output table || echo "⚠️  No tracer functions found or insufficient permissions"
        
        # Bootstrap CDK if needed
        echo "🚀 Bootstrapping CDK..."
        echo "📝 Note: CDK bootstrap is only needed once per AWS account/region"
        echo "🔄 If already bootstrapped, this will be skipped automatically"
        
        # Try to bootstrap, but don't fail if already bootstrapped
        if cdk bootstrap 2>&1 | grep -q "already bootstrapped\|already exists"; then
            echo "✅ CDK already bootstrapped - skipping"
        elif cdk bootstrap; then
            echo "✅ CDK bootstrap completed successfully"
        else
            echo "⚠️  CDK bootstrap failed or already bootstrapped - continuing with deployment"
        fi
        
        # Deploy the stack
        echo "🚀 Deploying CDK stack..."
        cdk deploy --require-approval never
        
        if [ $? -eq 0 ]; then
            echo "✅ Deployment completed successfully!"
            echo ""
            echo "📊 Stack outputs:"
            cdk list
            echo ""
            echo "🚀 Opening interactive shell for additional commands..."
            echo "💡 You can now run AWS CLI commands like:"
            echo "   aws lambda list-functions"
            echo "   aws s3 ls"
            echo "   aws sts get-caller-identity"
            echo "   cdk list"
            echo ""
            echo "Type 'exit' to leave the shell"
            echo ""
            
            # Start interactive shell
            exec /bin/bash
        else
            echo "❌ Deployment failed!"
            exit 1
        fi
        ;;
        
    "shell")
        if [ $# -ne 2 ]; then
            echo "❌ Error: shell command requires 1 argument (encrypted_credentials)"
            show_usage
            exit 1
        fi
        
        ENCRYPTED_CREDS="$2"
        
        echo "🔓 Decrypting credentials..."
        DECRYPTED_OUTPUT=$(python3 encrypt_utils.py decrypt "$ENCRYPTED_CREDS" 2>&1)
        
        if echo "$DECRYPTED_OUTPUT" | grep -q "Error:"; then
            echo "❌ $DECRYPTED_OUTPUT"
            echo ""
            echo "💡 Troubleshooting:"
            echo "1. Make sure you're using the exact hash generated by the 'hash' command"
            echo "2. Check that the hash hasn't been modified or truncated"
            echo "3. Try generating a new hash with: docker run --rm app hash <access_key> <secret_key> <region>"
            exit 1
        fi
        
        # Extract credentials from Python output
        ACCESS_KEY=$(echo "$DECRYPTED_OUTPUT" | grep "Access Key:" | cut -d' ' -f3)
        SECRET_KEY=$(echo "$DECRYPTED_OUTPUT" | grep "Secret Key:" | cut -d' ' -f3)
        REGION=$(echo "$DECRYPTED_OUTPUT" | grep "Region:" | cut -d' ' -f2)
        
        if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ] || [ -z "$REGION" ]; then
            echo "❌ Error: Failed to extract credentials from decryption output"
            echo "Debug output: $DECRYPTED_OUTPUT"
            exit 1
        fi
        
        echo "✅ Credentials decrypted successfully"
        echo "🌍 Region: $REGION"
        
        # Configure AWS CLI
        echo "⚙️  Configuring AWS CLI..."
        aws configure set aws_access_key_id "$ACCESS_KEY"
        aws configure set aws_secret_access_key "$SECRET_KEY"
        aws configure set region "$REGION"
        aws configure set output json
        
        # Test AWS connection
        echo "🔍 Testing AWS connection..."
        if aws sts get-caller-identity > /dev/null 2>&1; then
            echo "✅ AWS connection successful"
            IDENTITY=$(aws sts get-caller-identity --query 'Arn' --output text)
            echo "👤 Identity: $IDENTITY"
        else
            echo "❌ AWS connection failed. Please check your credentials."
            exit 1
        fi
        
        echo ""
        echo "🚀 Starting interactive shell with AWS credentials configured..."
        echo "💡 You can now run AWS CLI commands like:"
        echo "   aws lambda list-functions"
        echo "   aws s3 ls"
        echo "   aws sts get-caller-identity"
        echo "   cdk list"
        echo ""
        echo "Type 'exit' to leave the shell"
        echo ""
        
        # Start interactive shell
        exec /bin/bash
        ;;
        
    *)
        echo "❌ Unknown command: $1"
        show_usage
        exit 1
        ;;
esac 